In [1]:
# complex numbers : note the use of 'j' to denote the imaginary part
x = 1.0 - 1.0j
type(x)


complex

In [3]:
print(x.real, x.imag)

1.0 -1.0


In [5]:
import types


In [6]:
import types
print(dir(types))

['AsyncGeneratorType', 'BuiltinFunctionType', 'BuiltinMethodType', 'CodeType', 'CoroutineType', 'DynamicClassAttribute', 'FrameType', 'FunctionType', 'GeneratorType', 'GetSetDescriptorType', 'LambdaType', 'MappingProxyType', 'MemberDescriptorType', 'MethodType', 'ModuleType', 'SimpleNamespace', 'TracebackType', '_GeneratorWrapper', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', '_ag', '_calculate_meta', '_collections_abc', '_functools', 'coroutine', 'new_class', 'prepare_class']


In [7]:
print(help("__doc__"))

Help on str object:

__doc__ = class str(object)
 |  str(object='') -> str
 |  str(bytes_or_buffer[, encoding[, errors]]) -> str
 |  
 |  Create a new string object from the given object. If encoding or
 |  errors is specified, then the object must expose a data buffer
 |  that will be decoded using the given encoding and error handler.
 |  Otherwise, returns the result of object.__str__() (if defined)
 |  or repr(object).
 |  encoding defaults to sys.getdefaultencoding().
 |  errors defaults to 'strict'.
 |  
 |  Methods defined here:
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __format__(...)
 |      S.__format__(format_spec) -> str
 |      
 |      Return a formatted version of S as described by format_spec.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, 

In [8]:
type(x) is float

False

In [9]:
type(x) is complex

True

In [10]:
1 + 2, 1-2, 1*2,1/2

(3, -1, 2, 0.5)

In [3]:
def square(x):
    '''This is to return the square of any value'''
    return x*x

square(3)

9

In [10]:
def my_function(x, p=2, debug=False):
    if debug:
        print("evaluating for x=" + str(x) + " to the power of p="+ str(p))
    return x**p

my_function(5)

25

In [11]:
my_function(2, debug=True)

evaluating for x=2 to the power of p=2


4

In [14]:
list(map(lambda x: x**2, range(-3, 4)))


[9, 4, 1, 0, 1, 4, 9]

In [15]:
elements = [1,2,3,4,5]
double_elements = []

list(map(lambda x: x*2, elements))

[2, 4, 6, 8, 10]

In [18]:
##classes


In [23]:
''' Each class in python should always start with a SELF as the first argument'''
class Point:
    ''' A simple class that shows the points on a cartesian coordinate system'''
    def __init__(self, x,y):
        '''Create a new point at x and y'''
        self.x = x
        self.y = y
        
    def translate(self, dx, dy):
        '''
        Translate the point by dx and dy in the x and y direction.
        '''
        self.x += dx
        self.y += dy
        
    def __str__(self):
        return("Point at [%f, %f]" % (self.x, self.y))

In [24]:
p1 = Point(0,0) #this will invoke the __init__ method in the Point class
print(p1) #this will invoke the _-str__ method

Point at [0.000000, 0.000000]


In [25]:
p2 = Point(2,2)

In [26]:
print(p2)

Point at [2.000000, 2.000000]


In [27]:
p3 = p2.translate(2,4)
print(p3)

None


In [28]:
print(p2.translate(3,2))

None


In [29]:
p2.translate(0.23, 1.4)
print(p2)

Point at [7.230000, 9.400000]


In [30]:
%%file mymodule.py
'''
Example of a python module. Contains a variale called my_variable, a
function called my_function, and a class called MyClass.
'''
my_variable = 0

def my_function():
    '''
    Example function
    '''
    return my_variable

class MyClass:
    '''
    Example Class
    '''
    def __init__(self):
        self.variable = my_variable
        
    def set_variable(self, new_value):
        '''
        Set self.variable to a new value
        '''
        
        self.variable = new_value
        
    def get_variable(self):
        return self.variable

Writing mymodule.py


In [31]:
import mymodule
help(mymodule)

Help on module mymodule:

NAME
    mymodule

DESCRIPTION
    Example of a python module. Contains a variale called my_variable, a
    function called my_function, and a class called MyClass.

CLASSES
    builtins.object
        MyClass
    
    class MyClass(builtins.object)
     |  Example Class
     |  
     |  Methods defined here:
     |  
     |  __init__(self)
     |      Initialize self.  See help(type(self)) for accurate signature.
     |  
     |  get_variable(self)
     |  
     |  set_variable(self, new_value)
     |      Set self.variable to a new value
     |  
     |  ----------------------------------------------------------------------
     |  Data descriptors defined here:
     |  
     |  __dict__
     |      dictionary for instance variables (if defined)
     |  
     |  __weakref__
     |      list of weak references to the object (if defined)

FUNCTIONS
    my_function()
        Example function

DATA
    my_variable = 0

FILE
    /home/th3nn3ss/git_projects/mymodu

In [32]:
try:
    print('test')
    #generate an exception the value is not defined
    print(test)
except Exception as e:
    print("caught an error: " + str(e))
    

test
caught an error: name 'test' is not defined


In [34]:
try:
    print('Tring not to catch an error.')
    #This could generate an error
    print(str(test))
    
except Exception as e:
    print("Caught an exception:"+ str(e))

Tring not to catch an error.
Caught an exception:name 'test' is not defined


In [35]:
%load_ext version_information
%version_information

ModuleNotFoundError: No module named 'version_information'

In [36]:
#what is this line all about?!? Answer in lecture 4
%matplotlib inline
import matplotlib.pyplot as plt

ModuleNotFoundError: No module named 'matplotlib'

In [1]:
from numpy import *


ModuleNotFoundError: No module named 'numpy'

In [38]:
%load_ext version_information
%version_information

ModuleNotFoundError: No module named 'version_information'

In [39]:
%matplotlib inline 
import matplotlib.pyplot as plt

ModuleNotFoundError: No module named 'matplotlib'

In [2]:
from numpy import *

In [3]:
#a vector: the argument to the array function is the Python list
v = array([1,2,3,4])
v

array([1, 2, 3, 4])

In [4]:
#a matrix: the argument to the array function is a nested Python list
M = array([[1,2], [3,4]])
M

array([[1, 2],
       [3, 4]])

In [5]:
type(v), type(M)

(numpy.ndarray, numpy.ndarray)

In [6]:
v.shape, M.shape

((4,), (2, 2))

In [8]:
m = array([[1,2], [3,4]], dtype=complex)
m

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [10]:
#create a range
x = arange(0,10,1) #arguments: start, stop, step
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
x = arange(-1,1,0.1)
x

array([-1.00000000e+00, -9.00000000e-01, -8.00000000e-01, -7.00000000e-01,
       -6.00000000e-01, -5.00000000e-01, -4.00000000e-01, -3.00000000e-01,
       -2.00000000e-01, -1.00000000e-01, -2.22044605e-16,  1.00000000e-01,
        2.00000000e-01,  3.00000000e-01,  4.00000000e-01,  5.00000000e-01,
        6.00000000e-01,  7.00000000e-01,  8.00000000e-01,  9.00000000e-01])

In [12]:
linspace(0,10,0.1)

TypeError: object of type <class 'float'> cannot be safely interpreted as an integer.

In [13]:
linspace(0,10,25)

array([ 0.        ,  0.41666667,  0.83333333,  1.25      ,  1.66666667,
        2.08333333,  2.5       ,  2.91666667,  3.33333333,  3.75      ,
        4.16666667,  4.58333333,  5.        ,  5.41666667,  5.83333333,
        6.25      ,  6.66666667,  7.08333333,  7.5       ,  7.91666667,
        8.33333333,  8.75      ,  9.16666667,  9.58333333, 10.        ])

In [14]:
linspace(0,10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [15]:
logspace(0,10,base=10)

array([1.00000000e+00, 1.59985872e+00, 2.55954792e+00, 4.09491506e+00,
       6.55128557e+00, 1.04811313e+01, 1.67683294e+01, 2.68269580e+01,
       4.29193426e+01, 6.86648845e+01, 1.09854114e+02, 1.75751062e+02,
       2.81176870e+02, 4.49843267e+02, 7.19685673e+02, 1.15139540e+03,
       1.84206997e+03, 2.94705170e+03, 4.71486636e+03, 7.54312006e+03,
       1.20679264e+04, 1.93069773e+04, 3.08884360e+04, 4.94171336e+04,
       7.90604321e+04, 1.26485522e+05, 2.02358965e+05, 3.23745754e+05,
       5.17947468e+05, 8.28642773e+05, 1.32571137e+06, 2.12095089e+06,
       3.39322177e+06, 5.42867544e+06, 8.68511374e+06, 1.38949549e+07,
       2.22299648e+07, 3.55648031e+07, 5.68986603e+07, 9.10298178e+07,
       1.45634848e+08, 2.32995181e+08, 3.72759372e+08, 5.96362332e+08,
       9.54095476e+08, 1.52641797e+09, 2.44205309e+09, 3.90693994e+09,
       6.25055193e+09, 1.00000000e+10])

In [16]:
logspace(0,10, base=e)

array([1.00000000e+00, 1.22639826e+00, 1.50405270e+00, 1.84456762e+00,
       2.26217453e+00, 2.77432691e+00, 3.40242971e+00, 4.17273388e+00,
       5.11743359e+00, 6.27601167e+00, 7.69688981e+00, 9.43945230e+00,
       1.15765279e+01, 1.41974337e+01, 1.74117081e+01, 2.13536885e+01,
       2.61881265e+01, 3.21170729e+01, 3.93883224e+01, 4.83057703e+01,
       5.92421128e+01, 7.26544242e+01, 8.91032597e+01, 1.09276083e+02,
       1.34015998e+02, 1.64356988e+02, 2.01567124e+02, 2.47201571e+02,
       3.03167578e+02, 3.71804191e+02, 4.55980014e+02, 5.59213097e+02,
       6.85817972e+02, 8.41085969e+02, 1.03150637e+03, 1.26503762e+03,
       1.55143995e+03, 1.90268325e+03, 2.33344744e+03, 2.86173589e+03,
       3.50962792e+03, 4.30420159e+03, 5.27866536e+03, 6.47374603e+03,
       7.93939089e+03, 9.73685520e+03, 1.19412623e+04, 1.46447434e+04,
       1.79602878e+04, 2.20264658e+04])

In [17]:
logspace(0,10,1, base=10)

array([1.])

In [18]:
logspace(0,10 base=2)

SyntaxError: invalid syntax (<ipython-input-18-3d72bdde80a8>, line 1)

In [19]:
logspace(0,10, base=2)

array([1.00000000e+00, 1.15195282e+00, 1.32699530e+00, 1.52863599e+00,
       1.76091654e+00, 2.02849277e+00, 2.33672798e+00, 2.69180039e+00,
       3.10082705e+00, 3.57200647e+00, 4.11478293e+00, 4.74003581e+00,
       5.46029763e+00, 6.29000526e+00, 7.24578931e+00, 8.34680745e+00,
       9.61512839e+00, 1.10761743e+01, 1.27592302e+01, 1.46980313e+01,
       1.69314386e+01, 1.95042185e+01, 2.24679395e+01, 2.58820063e+01,
       2.98148502e+01, 3.43453008e+01, 3.95641662e+01, 4.55760529e+01,
       5.25014628e+01, 6.04792082e+01, 6.96691946e+01, 8.02556253e+01,
       9.24506940e+01, 1.06498838e+02, 1.22681637e+02, 1.41323458e+02,
       1.62797956e+02, 1.87535565e+02, 2.16032123e+02, 2.48858814e+02,
       2.86673613e+02, 3.30234477e+02, 3.80414538e+02, 4.38219601e+02,
       5.04808306e+02, 5.81515352e+02, 6.69878251e+02, 7.71668141e+02,
       8.88925293e+02, 1.02400000e+03])

In [20]:
mgrid(0:5,0:5)

SyntaxError: invalid syntax (<ipython-input-20-6abdec0147df>, line 1)

In [22]:
x,y = mgrid[0:5,0:5]

In [23]:
x

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

In [24]:
y

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [25]:
from numpy import random

In [26]:
!head stockholm_td_adj.dat

head: cannot open 'stockholm_td_adj.dat' for reading: No such file or directory


In [28]:
!head stockholm_td_adj.dat
1800 1 1 -6.1 -6.1 -6.1 1
1800 1 2 -15.4 -15.4 -15.4 1
1800 1 3 -15.0 -15.0 -15.0 1
1800 1 4 -19.3 -19.3 -19.3 1
1800 1 5 -16.8 -16.8 -16.8 1
1800 1 6 -11.4 -11.4 -11.4 1
1800 1 7 -7.6 -7.6 -7.6 1
1800 1 8 -7.1 -7.1 -7.1 1
1800 1 9 -10.1 -10.1 -10.1 1
1800 1 10 -9.5 -9.5 -9.5 1

SyntaxError: invalid syntax (<ipython-input-28-bb49b7971ff8>, line 2)

In [29]:
!head stockholm_td_adj.dat


1800 1 1 -6.1 -6.1 -6.1 1
1800 1 2 -15.4 -15.4 -15.4 1
1800 1 3 -15.0 -15.0 -15.0 1
1800 1 4 -19.3 -19.3 -19.3 1
1800 1 5 -16.8 -16.8 -16.8 1
1800 1 6 -11.4 -11.4 -11.4 1
1800 1 7 -7.6 -7.6 -7.6 1
1800 1 8 -7.1 -7.1 -7.1 1
1800 1 9 -10.1 -10.1 -10.1 1
1800 1 10 -9.5 -9.5 -9.5 1


In [30]:
data = getfromtext(stockholm_td_adj.dat)

NameError: name 'getfromtext' is not defined

In [31]:
data = getfromtxt(stockholm_td_adj.dat)

NameError: name 'getfromtxt' is not defined

In [32]:
data = genfromtxt('stockholm_td_adj.dat')

In [33]:
data.size

70

In [34]:
data.shape

(10, 7)